/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONevent {
  eventname: string;
  date: Date;
  place: string;
  rooms: any[];
  groups?: any[];
  guests?: any[];
}
